### ISSUE TITLE
Trouble opening FOQUS

### ISSUE THREAD

**Issue by fsoepyan** [CCSI-Toolset/FOQUS#387]
- I have Anaconda 3
- I downloaded FOQUS from GitHub
- I followed Steps 8 and 9 from Install.md
- When I tried opening FOQUS, I got an error message, and FOQUS won't open:

<img width="434" alt="foqus_02_13_2019" src="https://user-images.githubusercontent.com/30811140/52738362-7cfefc80-2f9c-11e9-8d87-94c129e82e1a.png">

**Comment by fsoepyan** [comment]
- I followed the installation instructions.
- I also did what @ksbeattie suggested, which is to do pip uninstall on both py-dateutil and python-dateutil, and do pip install python-dateutil.
- Unfortunately, I still got the same error messages that I got in #390, and FOQUS won't open:

<img width="420" alt="foquswontopen_02_20_2019" src="https://user-images.githubusercontent.com/30811140/53116278-48e48800-3516-11e9-84e5-6df826c7c254.png">
<img width="415" alt="foquswontopen2_02_20_2019" src="https://user-images.githubusercontent.com/30811140/53116279-4aae4b80-3516-11e9-8956-8c11e111189f.png">

**Comment by candcook** [comment]
Towfiq and I tried to install the new version of FOQUS on both a Windows machine and a Mac ... we encountered the same problems as Byron. It seems to require turbine to be installed after manually installing lumpy and pandas. In the documentation it suggests that turbine should be optional.

**Comment by atowfiq** [comment]
Pedro Sotorrio helped me this evening to finally figure out the FOQUS installation issues similar to Issue#387 for windows installation. 
Here are the steps we took which worked on two of my windows 10 machines for fresh FOQUS installation:
(1) >> conda  env create –f foqus_env.yml  (this sets up the environment including several libraries except for turbine)
(2) >> conda activate foqus_env
     At this point if ‘git’ is not already installed, do >> conda install git
(3) >> pip install –r requirements.txt (most libraries will already be installed in step (1). But this will make sure turbine client is installed and configured).
(4) >> python setup.py install    
(5) >> python foqus.py   
If complains about py-dateutil, then follow these steps:
(6) >> pip uninstall py-dateutil   and >> pip uninstall python-dateutil.
	Then >> conda install python-dateutil
Then GUI should start working and ask for a ‘working directory’. Once specified, it might fail again (DLL load failure) due to PyQt5.  Downgrading PyQt5 library from 5.12 to 5.9 solved this problem: 
(7) >> pip install PyQT5==5.9
(8) >> python foqus.py   --> now should start FOQUS  as it did successfully in my two windows 10 machines. 
Thanks Pedro.

**Comment by candcook** [comment]
Thanks Towfiq,

Unfortunately, I got stuck on the first command ….


pn1808529:FOQUS-master candcook$ conda env create -f foqus_env.yml

Solving environment: failed



ResolvePackageNotFound:

  - pywin32

It seems that it somehow wants that pywin32 package to be there … and not sure how to make that happen on a mac machine.
Any thoughts?

Thanks,
Christine

**Comment by fsoepyan** [comment]
@sotorrio1 and @atowfiq: Thank you! Your instructions work, and I can now open FOQUS.

**Comment by sotorrio1** [comment]
@candcook I sent you an email. Basically for Mac you need to comment out/delete the line that contains pywin32 in the environment file ('foqus_env.yml') since it's a Windows-only package.

**Comment by candcook** [comment]
Thanks Pedro …. That helped me get a bit further … but still get an error:


pn1808529:FOQUS-master candcook$ conda activate foqus_env



(foqus_env) pn1808529:FOQUS-master candcook$ pip install -r requirements.txt

Ignoring adodbapi: markers 'sys_platform == "win32"' don't match your environment

Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment

Collecting git+https://git@github.com/CCSI-Toolset/turb_client (from -r requirements.txt (line 14))

  Cloning https://git@github.com/CCSI-Toolset/turb_client to /private/var/folders/zm/ldz_d36s6mz3j_vryr74xcyw0000gp/T/pip-req-build-8sdjzs_c

fatal: unable to access 'https://git@github.com/CCSI-Toolset/turb_client/': Failed to connect to github.com port 443: Connection refused

Command "git clone -q https://git@github.com/CCSI-Toolset/turb_client /private/var/folders/zm/ldz_d36s6mz3j_vryr74xcyw0000gp/T/pip-req-build-8sdjzs_c" failed with error code 128 in None

I think it failed there earlier when Towfiq was trying to help.

Sorry to be a rookie at sorting out these problems for myself.

Thanks,
Christine

**Comment by sotorrio1** [comment]
@candcook it looks like you are having some permission issues cloning the turbine-client repo... are you logged in with your GitHub username?

**Comment by eslickj** [comment]
I think this is fixed in PR #410.  I set the version of PyQt in requirements.txt.  I updated the FOQUS install instructions not to use the yaml files.  Pywin32 is conditionally installed in windows only in requirements.txt. If PR #410 dosn't fix these issues let me know.

**Comment by ksbeattie** [comment]
@candcook can you test this again, now that @eslickj has made a change he thinks may have fixed things?

**Comment by candcook** [comment]
It is still not working ... it seems that the instruction on the github site are not current. In FOQUS-2.5.0 there does not seem to be a requirements.txt file.
I also get an error when I try to run 
python setup.py
(foqus) pn1808529:FOQUS-2.5.0 candcook$ python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    import foqus_lib.version.version as ver
  File "/Users/candcook/Documents/CMACFiles/Work folders/CCSI-wf/FOQUS-2.5.0/foqus_lib/version/version.py", line 51
    print version
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(version)

**Comment by sotorrio1** [comment]
@candcook that last error with the print statement it's related to your Python version. In Python 2 there was no need for parentheses in the printing call, in Python 3 there is. Are you trying to run the py2 branch on your python 3 environment?

**Comment by candcook** [comment]
With Towfiq's help I was able to make it further this time ...

When I do :
pip install -r requirements.txt

I get the following error:
Command "git clone -q https://git@github.com/CCSI-Toolset/turb_client /private/var/folders/zm/ldz_d36s6mz3j_vryr74xcyw0000gp/T/pip-req-build-4ply58s_" failed with error code 128 in None

which I think is a permissions problem on the LANL network that my computer is on. It was my impression that turbine was optional, but when I comment out the statement for turbine, I am able to proceed a bit further, but then I get an error when I try to run:
python foqus.py
the error is:
ModuleNotFoundError: No module named 'turbine'
which suggests it is not optional.

Any advice would be appreciated.

**Comment by ksbeattie** [comment]
@sotorrio1 it looks to me like @candcook is using the last release (note the `/FOQUS-2.5.0/` in the path).

@candcook, can you test again by getting FOQUS one of the following ways:
- Download the [2.6.0 release candidate](https://github.com/CCSI-Toolset/FOQUS/releases/tag/2.6.0.rc1) I just created
- Click the green `Clone or download` button at the main [github FOQUS page](https://github.com/CCSI-Toolset/FOQUS) and get the latest dev version by either using git clone (as instructed there) or downloading is all as a ZIP file.

Also, I believe @CSRussell2319 has some tricks for working behind the LANL firewalls

**Comment by candcook** [comment]
I downloaded the new version and then did 
conda install git   
(worked fine)
and
conda install git
and got this error message:
(base) pn1808529:FOQUS-master candcook$ python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    import foqus_lib.version.version as ver
  File "/Users/candcook/Documents/CMACFiles/Work folders/CCSI-wf/FOQUS-master/foqus_lib/version/version.py", line 51
    print version
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(version)?

I checked and I am running these versions
pn1808529:FOQUS-master candcook$ conda --version
conda 4.5.12
pn1808529:FOQUS-master candcook$ python --version
Python 3.7.1

Thoughts?

**Comment by CSRussell2319** [comment]
I've emailed @candcook and will attempt to troubleshoot issues. I think it will be easier for me to work with the computer on-site.

**Comment by sotorrio1** [comment]
Thanks @CSRussell2319 
Obviously there is something odd with the file 'version.py' since it should have the parentheses for the printing statement.

**Comment by eslickj** [comment]
Version.py shouldn't have any print staments anymore.  They should have been removed a while ago.  Version.py is generated first thing in setup.py by adding a version number to version.template.   Grab the latest foqus and delete version.py.  Either it's an old version of foqus or version.py is not being generated for some reason.  You shouldn't need to delete it but at least that way you'll know for sure if it is generated.

**Comment by candcook** [comment]
I removed the old version.py and still get the same error ... I checked a new version is being created, so whatever is generating it, seems to be introducing the error.

I have the latest version of the foqus that I downloaded yesterday as per Keith's instructions.

Still a mystery! I will try to get with Chris Russell on Monday to see if he can help resolve this here in person.

**Comment by sotorrio1** [comment]
the issue with py-dateutil and python-dateutil is not happening anymore. I installed FOQUS on a fresh VM and I only needed the following commands:

- conda create -n foqus python=3
- conda activate foqus
- pip install –r requirements.txt
- python setup.py install

**Comment by CSRussell2319** [comment]
I went by @candcook office and we were able to set up foqus and get it to launch on Mac. I'm in the process of verifying instructions so new updates can be installed easily without my involvement.

**Comment by eslickj** [comment]
These problems should be solved. At least this is carrying on to issue #427, which may also be resolved already.
